# coding=utf-8
#
# Copyright 2025
# Heinrich Heine University Dusseldorf,
# Faculty of Mathematics and Natural Sciences,
# Computer Science Department
#
# Authors:
# Renato Vukovic (renato.vukovic@hhu.de)
#
# This code was generated with the help of AI writing assistants
# including GitHub Copilot, ChatGPT, Bing Chat.

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

#     http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# # # # # # # # # # # # # # # # # # # # # # # # # # # # #

from dataclasses import dataclass, asdict
from typing import List

@dataclass
class hallucination_detection_config():
	model_name: str  # name of the model
	dataset: str  # name of the dataset
	tasktype: str # task type in rag truth dataset
	splits: List[str]  # list of splits to be used for the prediction
	max_tokens: int = 4096  # maximum number of new tokens to be generated by the model
	prompt_name: str = "baseline"  # prompt for the model
	seed: int = None #seed to set for different samples for the same prompt
	return_column_values: bool = False #whether to add column value examples in pragma queries


	#method for returning the config params as a dict for saving as json
	def to_dict(self):
		return asdict(self)
		